class Inspection {
  String? inspectionId;
  DateTime date;
  String comments;
  int status;

  Inspection({
    this.inspectionId,
    required this.date,
    required this.comments,
    required this.status,
  });

  void setAutogeneratedId(String id) {
    inspectionId = id;
  }
}
