class Inspection {
  String? inspectionId;
  DateTime date;
  String comments;
  int status;
  // List<Map<String, bool>> checkList = [];

  Inspection({
    this.inspectionId,
    required this.date,
    required this.comments,
    required this.status,
    // required this.checkList,
  });

  void setAutogeneratedId(String id) {
    inspectionId = id;
  }
}
