import 'package:under_control_flutter/models/checklist.dart';

class Inspection {
  String? inspectionId;
  DateTime date;
  String comments;
  int status;
  Checklist? checklist;

  Inspection({
    this.inspectionId,
    required this.date,
    required this.comments,
    required this.status,
    this.checklist,
  });

  void setAutogeneratedId(String id) {
    inspectionId = id;
  }
}
