import 'dart:io';

enum TaskStatus { planned, started, completed }

enum TaskType { event, inspection, reparation, maintenance }

enum TaskExecutor { company, user, all }

class Task {
  String? taskId;
  String title;
  DateTime date;
  DateTime? reminderDate;
  TaskExecutor executor;
  String? itemId;
  String description;
  String comments;
  TaskStatus status;
  TaskType type;
  List<File>? images;

  Task({
    this.taskId,
    required this.title,
    required this.date,
    this.reminderDate,
    required this.executor,
    this.itemId,
    required this.description,
    required this.comments,
    required this.status,
    required this.type,
    this.images,
  });

  void setAutogeneratedId(String id) {
    itemId = id;
  }
}
