import 'dart:io';

class Task {
  String? taskId;
  String title;
  DateTime date;
  DateTime? reminderDate;
  String? executor;
  String? itemId;
  String description;
  String comments;
  int status;
  List<File>? images;

  Task({
    this.taskId,
    required this.title,
    required this.date,
    this.reminderDate,
    this.executor,
    this.itemId,
    required this.description,
    required this.comments,
    required this.status,
    this.images,
  });

  void setAutogeneratedId(String id) {
    itemId = id;
  }
}
