// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATKjVuDVvCMsyQXTGtb4hJIRt4_n4Ucb0',
    appId: '1:1000722485536:web:e81ef13cec51b7c6aec745',
    messagingSenderId: '1000722485536',
    projectId: 'under-control-flutter',
    authDomain: 'under-control-flutter.firebaseapp.com',
    storageBucket: 'under-control-flutter.appspot.com',
    measurementId: 'G-P4EVCTFEV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7mFFsLT4OD10ik0x9627yXt4L8yDawvo',
    appId: '1:1000722485536:android:e28903d069fcff03aec745',
    messagingSenderId: '1000722485536',
    projectId: 'under-control-flutter',
    storageBucket: 'under-control-flutter.appspot.com',
  );
}
